apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: springpetclinic-dev
  name: springpetclinic-dev
  namespace: springpetclinic-dev
spec:
  host: petspringclinic-dev-springpetclinic-dev.apps.containers.aws-ocp.dev.uspto.gov
  port:
    targetPort: 8080
  to:
    kind: Service
    name: springpetclinic-dev
    weight: 100
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
