apiVersion: v1
kind: Service
metadata:
  labels:
    app: springpetclinic-dev
  name: springpetclinic-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springpetclinic-dev
